### ISSUE TITLE
Claim Rewards 

### ISSUE THREAD

**Issue by dziedom** [Zilliqa/Zillion-issue#11]
From a CX perspective when Claiming  Rewards should the UI not  only show the seed nodes I have staked against,  rather than the whole list. In this case I had only staked on two seeds nodes, so I would only expect to see 2 seed nodes.

![Claim Rewards](https://user-images.githubusercontent.com/62773889/93709528-b9aab680-fb36-11ea-83cd-98cfc1181fba.png)

**Comment by AmritKumar** [comment]
This is fixed now. Thanks for reporting it. I am closing this for now.
![image](https://user-images.githubusercontent.com/4191868/94140548-4caf5d80-fe63-11ea-86c8-4592a4b2077c.png)

**Comment by xyn1nja** [comment]
Hello @dziedom we'd like to reward you for your submission, can you provide your ZIL wallet address please? Thanks!

**Comment by dziedom** [comment]
Thanks great job with the user experience  zil1d95l903zq9wg80mfy6x5mragnek55qc8vrf96a Sent from Mail for Windows 10 From: xyninja000Sent: 27 October 2020 04:08To: Zilliqa/Zillion-issueCc: dziedom; MentionSubject: Re: [Zilliqa/Zillion-issue] Claim Rewards (#11) Hello @dziedom we'd like to reward you for your submission, can you provide your ZIL wallet address please? Thanks!—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.
