### ISSUE TITLE
ReDelegate Stake - Greyed Out 

### ISSUE THREAD

**Issue by dziedom** [Zilliqa/Zillion-issue#13]
ReDelegate Stake –  If nothing was staked I would expect the ReDelegate Stake to be greyed out ? 

![Greyed Out](https://user-images.githubusercontent.com/62773889/93709733-97199d00-fb38-11ea-8796-0310f264e740.JPG)

**Comment by AmritKumar** [comment]
Thanks for the input. You will see this in the fixed version. Closing it for now.

![image](https://user-images.githubusercontent.com/4191868/94534419-42f97180-0238-11eb-91f0-3249a0e73df6.png)
