### ISSUE TITLE
ReDelegate Stake - DropDown Menu

### ISSUE THREAD

**Issue by dziedom** [Zilliqa/Zillion-issue#14]
On the dropdown list of operators delegated too, it should only show the ones i have currently delegated on rather than the whole list, makes for a better UX. 

![ReDelegate](https://user-images.githubusercontent.com/62773889/93709779-20c96a80-fb39-11ea-9e8b-2549c8d0ab62.png)

**Comment by AmritKumar** [comment]
This is fixed now. It only shows the operators with which you have currently staked. Thanks for reporting this. I am closing this for now. ![image](https://user-images.githubusercontent.com/4191868/94140300-f2160180-fe62-11ea-8e24-4bc00391671c.png)
