### ISSUE TITLE
Trouble Re-Delegating using Ledger Nano S

### ISSUE THREAD

**Issue by FlipOne513** [Zilliqa/Zillion-issue#15]
When I try to re-delegate tokens from one operator to another I get an error message.  Now i'm trying to withdraw some tokens so I can delegate them manually vs just re-delegating them.  Withdraw has been pending for 15 or 20 minutes now, seems like it shouldn't take that long all other transactions happened within 1 to 3 minuets.

**Comment by FlipOne513** [comment]
withdraw still pending hours later.

**Comment by AmritKumar** [comment]
Can you post a transaction hash for the re-delegation error? Withdrawal of stake is not fully pushed in the UI yet. It will be a two-step process. You should try it out in the next few days. Thanks for reporting the issue.

**Comment by AmritKumar** [comment]
You should try this now. We have now enabled stake withdrawals. Closing this for now. In case this does not fix your issue, feel free to open it back?
