### ISSUE TITLE
Unclaimed GZIL Rewards: Confusing

### ISSUE THREAD

**Issue by 10131** [Zilliqa/Zillion-issue#16]
How do you claim the GZIL? There is no option under Claim Rewards when you click on the button. Also, I think the calculation is wrong since I just staked 4900 zil within 30 secs. It's a bit confusing.

Overall looking good ZIL Team!

![noclaim_info](https://user-images.githubusercontent.com/71618874/93729308-cc45df80-fb78-11ea-80cc-852d7aa15100.jpg)

**Comment by dziedom** [comment]
I'm experiencing the same thing, although in my instance I have been able to claim some gZil previously but the remainder I can't access.  When it says unclaimed does that mean I can claim it at any time?  Should there be a button that says claim Zil rewards and a separate one for  claiming  GZil rewards?

![Unclaimed Gzil](https://user-images.githubusercontent.com/62773889/93763769-eaa7eb80-fc09-11ea-9af4-93aebeede274.JPG)

**Comment by AmritKumar** [comment]
gZILs are claimed at the same time staking rewards are claimed. They do not need to be claimed separately. The overview section had a bug which showed incorrect unclaimed gZIL balance. This has been fixed. Thanks for reporting.

**Comment by xyn1nja** [comment]
Hello @10131 we'd like to reward you for your submission, can you provide your ZIL wallet address please? Thanks!

**Comment by 10131** [comment]
@xyninja000 oh, great! Glad to have been part of this. I have lots of confidence in you guys. Here's an address: 
zil12j7wle24qu4tdjkkm087rjvz5ujx8vtv65tr6z
