### ISSUE TITLE
withdraw issue

### ISSUE THREAD

**Issue by themadboris** [Zilliqa/Zillion-issue#18]
set to withdraw 3k zil, transaction was succes it going to pending balance, after if I try to withdraw another amount of coins it shows error: https://viewblock.io/zilliqa/tx/5d760b41839a73c13d780662bb00e5dcc44b6f5ec93cc93b44719dde1e292a7d?network=testnet

**Comment by themadboris** [comment]
balance is not show on zillion, and was not recived on wallet.. where is it ? :)

**Comment by themadboris** [comment]
~3 days my withdraw 3k. stay in pending.. it's normal ?

**Comment by themadboris** [comment]
![z](https://user-images.githubusercontent.com/54707648/93976703-a8052100-fd79-11ea-94eb-fea4fc65bf68.jpg)

**Comment by AmritKumar** [comment]
Staking withdrawal is not fully available in the UI yet. Please try after a few days.

**Comment by AmritKumar** [comment]
You should try this again. I am closing this for now. Thanks again for reporting this.
![image](https://user-images.githubusercontent.com/4191868/94141120-2fc75a00-fe64-11ea-959c-42231b50d20f.png)

**Comment by xyn1nja** [comment]
Hello @themadboris we'd like to reward you for your submission, can you provide your ZIL wallet address please? Thanks!

**Comment by themadboris** [comment]
Hi, thx, zil1nkst9z8envmap64sd6l8qxrz9t2pz95xvgxlzt

вт, 27 окт. 2020 г., 05:10 xyninja000 <notifications@github.com>:
