### ISSUE TITLE
Delegate Stake Drop Down – User Experience 

### ISSUE THREAD

**Issue by dziedom** [Zilliqa/Zillion-issue#19]
When you go to delegate stake in the drop down list  it may help to have the operator offering the highest commission rate at the top of the list and rank in order of commission return rate.  There doesn’t seem to be a rational to the order currently i.e. its not even in Alphabetical order.

![Delegate Stake Drop Down list](https://user-images.githubusercontent.com/62773889/93758288-0efeca80-fc00-11ea-8008-da11beee079c.png)

**Comment by AmritKumar** [comment]
We have changed the UI for staking now. This should not be an issue anymore. Closing it for now.
![image](https://user-images.githubusercontent.com/4191868/95294017-7194cf00-086c-11eb-82c7-bd47ec9bca92.png)
