### ISSUE TITLE
Gzil reward ratio is incorrect 

### ISSUE THREAD

**Issue by ghost** [Zilliqa/Zillion-issue#2]
![A77BF9A9-0B50-4F7D-8FFD-AEE142987CAE](https://user-images.githubusercontent.com/71545485/93662297-7272e600-faa2-11ea-8222-d1b4f5bc5f72.jpeg)

**Comment by ghost** [comment]
I have accumulated zero Zil rewards as I have just started staking. Yet I have accumulated 0.488 gzil

**Comment by AmritKumar** [comment]
This is indeed a bug in the UI. It has been fixed. Thanks for reporting this. I am closing this for now.

**Comment by xyn1nja** [comment]
Hello @casper10222 we'd like to reward you for your submission, can you provide your ZIL wallet address please? Thanks!

**Comment by ghost** [comment]
Thank you, that is really good news. I appreciate it.


zil1ktur8e3ufzt0xk5zqjep8wepndp6udwyyre86l

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by ghost** [comment]
Did you receive my address correctly

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by xyn1nja** [comment]
Hi @casper10222 yes I did, thanks for providing your address. Please allow for a few days for your rewards to be issued.

**Comment by ghost** [comment]
Cool thanks 🙏🏼

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by ghost** [comment]
Can I request to be emailed once the reward has been issued? I keep checking, thanks guys

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by xyn1nja** [comment]
Hi @casper10222 your reward should be in now, thanks!
