### ISSUE TITLE
Can't send ZIL: "Insufficient funds in source account!"

### ISSUE THREAD

**Issue by ZILLI0N** [Zilliqa/Zillion-issue#21]
Reproduction:
- go to https://dev-wallet.zilliqa.com/send
- access existing testnet wallet (my example wallet has 5000 ZIL)
- send ZIL to another wallet (tried different amounts between 1000-5000 ZIL)
- Observe: Gas Price 0.001 ZIL
- Confirm -> Insufficient funds in source account!

**Comment by AmritKumar** [comment]
It does not seem to be an issue with Zillion. I guess the faucet ran out of funds when you tried to call. Closing this for now.
