### ISSUE TITLE
Dashboard link goes to empty page after signing out

### ISSUE THREAD

**Issue by ZILLI0N** [Zilliqa/Zillion-issue#22]
Going to https://testnet-stake.zilliqa.com/dashboard results in an empty page after signing out. Should probably go to main page

**Comment by AmritKumar** [comment]
Thanks for the input. Dashboard is specific to a given user. So, if a user is logged out and tried to go to the dashboard he will see the following error screen. I am closing this for now.
![image](https://user-images.githubusercontent.com/4191868/94535045-00846480-0239-11eb-97cc-4ec14b5ec8c6.png)

**Comment by xyn1nja** [comment]
Hello @ZILLI0N we'd like to reward you for your submission, can you provide your ZIL wallet address please? Thanks!

**Comment by ZILLI0N** [comment]
hey @xyninja000 
here is my ZIL wallet address
zil1548wsm3rda0qq9pljv09daz7s2yzxtz4lumhgv
are the gZil's from the test wallets transferrable to the mainnet, or are they also just for testing?
thanks!

**Comment by xyn1nja** [comment]
Hi @ZILLI0N, testnet gZIL and ZIL cannot be transferred to the mainnet. Thanks!
