### ISSUE TITLE
Attempt at staking 0 or "-0" ZIL gets processed, spending ZIL in the process

### ISSUE THREAD

**Issue by ZILLI0N** [Zilliqa/Zillion-issue#26]
When you stake 0 or -0 ZIL it is actually processed and you spend ZIL. 

Furthermore, when you try to stake with a negative amount, you can click on the Stake button and it is also processed. But you don't waste ZIL, instead you get the following error:
There is an error, please try again

So it would make sense to check if the value is greater than 0 and show an error otherwise. Like the error shown for non numerical characters: Delegate amount is invalid.

**Comment by AmritKumar** [comment]
Thanks for reporting this. It is fixed. Closing it for now.  ![image](https://user-images.githubusercontent.com/4191868/94261989-a4fd6280-ff2a-11ea-8323-707511c35134.png)
