### ISSUE TITLE
No staking reward from Moonlet.io staking node

### ISSUE THREAD

**Issue by devarshdpatel** [Zilliqa/Zillion-issue#28]
Team, 

I have been staking across multiple staking nodes since past 2 days. However, I see 0 rewards from Moonlet.io staking node. Staking should work seamlessly across all the staking nodes when delegator decides to stake across multiple nodes. 

Screen-prints:-
[Staking not working Moonlet.io.docx](https://github.com/Zilliqa/Zillion-issue/files/5262350/Staking.not.working.Moonlet.io.docx)

**Comment by devranjan** [comment]
The same issue, I have faced. There is no reward from Zillacracy stacking node. 
Here is the transaction detail for the reward request. Received 0 gzil:

https://viewblock.io/zilliqa/tx/0xa89a5fb6aca15c27f49801bd424a76656416e6f57709e70f9b6f2d14d5e5515b?network=testnet

![no rewards for stack](https://user-images.githubusercontent.com/11460583/93977312-e9a4c480-fd97-11ea-8ade-0780b7c79152.PNG)

**Comment by AmritKumar** [comment]
Thanks for reporting the issue. For some time the two nodes were not healthy and hence were not receiving rewards. I am closing this for now.
