### ISSUE TITLE
Transfer Stake

### ISSUE THREAD

**Issue by dziedom** [Zilliqa/Zillion-issue#29]
When i try to transfer stake from Pickachu  to sentinal it throws an error saying it needs to be a bech32 address

**Comment by dziedom** [comment]
When i try to transfer stake from Pickachu to sentinal it throws an error saying it needs to be a bech32 address
![bech32](https://user-images.githubusercontent.com/62773889/93903747-fc17f300-fcf0-11ea-9bbd-d3d448dadbbd.png)

**Comment by AmritKumar** [comment]
We are not able to reproduce this. Is there any more info you could provide? Thanks!

**Comment by AmritKumar** [comment]
It should be fixed now. Thanks for reporting it. I am closing it for now.
