### ISSUE TITLE
UNCLAIMED GZIL REWARDS displayed for delegator with 0 deposit

### ISSUE THREAD

**Issue by SuhasShelke** [Zilliqa/Zillion-issue#3]
Delegator logs in with fresh wallet on zillon. However, delegator is displayed non zero UNCLAIMED GZIL REWARDS despite depositing 0 zil in any of the seed nodes. 

Issues is explained in detail in attached word doc.
[UX Issue.docx](https://github.com/Zilliqa/Zillion-issue/files/5249688/UX.Issue.docx)

**Comment by AmritKumar** [comment]
This is a bug in the UI and has been fixed since. Thanks for reporting it. I am closing this for now.

**Comment by xyn1nja** [comment]
Hello @SuhasShelke we'd like to reward you for your submission, can you provide your ZIL wallet address please? Thanks!

**Comment by SuhasShelke** [comment]
> Hello @SuhasShelke we'd like to reward you for your submission, can you provide your ZIL wallet address please? Thanks!

Hi @xyninja000 thanks a lot for the consideration. My ZIL wallet address is as below. Highly appreciate this :)

zil17wu9mf9w29vutw4hqjk5zlpjw9v85hczegrdgn
