### ISSUE TITLE
Confirm or reject action

### ISSUE THREAD

**Issue by Jotka108** [Zilliqa/Zillion-issue#31]
if you want to perform an action with the Zilpay app, a window opens. But it is not obvious how to execute the action. Only by searching and by chance you might realize that you have to click on the cube to open the execution window. (Telegram: My Cosmos)

![ZilUnclearStep](https://user-images.githubusercontent.com/36862733/93919154-95ed9900-fd0d-11ea-9798-fb09d6a32351.JPG)

**Comment by AmritKumar** [comment]
It's a ZilPay issue. Will close it.
