### ISSUE TITLE
Blank page after refreshing the logged-in wallet - Suggestion

### ISSUE THREAD

**Issue by devranjan** [Zilliqa/Zillion-issue#33]
After refreshing the already logged-in wallet page return a blank page. Even it shows an error of losing the connection of the wallet while refreshing, It should either show:
(1) the same logged-in wallet,
(2) log-out and return to the home page of the wallet app, or
(3) log-out and ask to re-login to access the wallet.

It's only my suggestion.

![Zilliqa page refresh error](https://user-images.githubusercontent.com/11460583/93935270-f8608c80-fd41-11ea-996f-210b30f06424.gif)

**Comment by AmritKumar** [comment]
Thanks for the input. We have gone with 3 for now. I am closing this for now.
![image](https://user-images.githubusercontent.com/4191868/94533455-0aa56380-0237-11eb-865e-a03436bff01a.png)
