### ISSUE TITLE
Transfer Stack error

### ISSUE THREAD

**Issue by devranjan** [Zilliqa/Zillion-issue#34]
It throws an error while transferring stake from one stack address to another.

![Error in transferring stake](https://user-images.githubusercontent.com/11460583/93976751-15737a80-fd97-11ea-94c3-40a8ed0eb84b.gif)

**Comment by AmritKumar** [comment]
Good catch! This is indeed a bug. We will fix it. I will keep this issue open for now.

**Comment by AmritKumar** [comment]
This is fixed now. Thanks for reporting it. I am closing it for now.

**Comment by devranjan** [comment]
> This is fixed now. Thanks for reporting it. I am closing it for now.

It's my pleasure. 🙂
