### ISSUE TITLE
remove blue border after clicking buttons

### ISSUE THREAD

**Issue by mwansich** [Zilliqa/Zillion-issue#35]
After clicking on one of the four buttons a blue border appears around them. This is useless because a modal window is opened anyway and after closing it i dont need the information that i clicked that button. Hence the button having that blue border just looks strange and provides nothing. Just a minor issue but thus also easy to resolve.

![Screenshot 2020-09-24 at 14 12 32](https://user-images.githubusercontent.com/70520740/94143368-06143000-fe70-11ea-83bc-bad57839809a.jpg)

**Comment by AmritKumar** [comment]
Thanks for the suggestion. This should not appear in the new UI anymore. 
![image](https://user-images.githubusercontent.com/4191868/95293671-ce43ba00-086b-11eb-839a-f49e71102745.png)

Closing it for now.
