### ISSUE TITLE
Include Commission Rate

### ISSUE THREAD

**Issue by DicksonLaiSuleiman** [Zilliqa/Zillion-issue#36]
Improve user experience, to include commission rate of Operator in the option list when selecting operator to delegate stake to.
<img width="957" alt="Screenshot 2020-09-26 at 4 56 51 PM" src="https://user-images.githubusercontent.com/31592055/94336936-4b279600-0019-11eb-9fd0-99c077c2f2b6.png">

**Comment by AmritKumar** [comment]
Thanks for the suggestion. We have fixed this in the updated UI. 
![image](https://user-images.githubusercontent.com/4191868/95293588-9e94b200-086b-11eb-9147-968b27242e71.png)

Closing it for now.

**Comment by xyn1nja** [comment]
Hello @DicksonLaiSuleiman we'd like to reward you for your submission, can you provide your ZIL wallet address please? Thanks!

**Comment by DicksonLaiSuleiman** [comment]
Hi,

You can send to my ZIL wallet address at:

zil1rj7q0qdll88draf4kduuqec8vy8m8k47kfv92q

Thank you!

Dickson Lai
