### ISSUE TITLE
Add stake button next to operator seed node in list of Staked Seed Nodes.

### ISSUE THREAD

**Issue by DicksonLaiSuleiman** [Zilliqa/Zillion-issue#37]
Improve User Experience, shorten steps required to stake to desired seed node operator.
<img width="1193" alt="Screenshot 2020-09-26 at 4 58 11 PM" src="https://user-images.githubusercontent.com/31592055/94336989-a2c60180-0019-11eb-906c-53f49eb209fc.png">

**Comment by AmritKumar** [comment]
Thanks for the suggestion. We are thinking about it too. I will leave this open for now.

**Comment by AmritKumar** [comment]
We have fixed this. ![image](https://user-images.githubusercontent.com/4191868/95293455-5bd2da00-086b-11eb-8715-bc129a676d5c.png). Closing it for now.
