### ISSUE TITLE
Re-Delegate Stake, Withdraw Stake and Claim Rewards buttons are enabled for Delegator with 0 deposit

### ISSUE THREAD

**Issue by SuhasShelke** [Zilliqa/Zillion-issue#4]
When delegator logs in with fresh wallet and has 0 deposits or no staking, Re-Delegate Stake, Withdraw Stake and Claim Rewards buttons should be disabled and only Delegate Stake button should be enabled.

Please refer attached document for further details.
[UX Issue2.docx](https://github.com/Zilliqa/Zillion-issue/files/5249746/UX.Issue2.docx)

**Comment by AmritKumar** [comment]
Thanks for the input. We have changed the UI to so that users won't see any operator if they haven't delegated yet. I am closing this for now. 
![image](https://user-images.githubusercontent.com/4191868/94534019-d54d4580-0237-11eb-9619-f49f9eff3131.png)
