### ISSUE TITLE
Failed transaction on blockchain when delegator proceeds with claim rewards

### ISSUE THREAD

**Issue by SuhasShelke** [Zilliqa/Zillion-issue#5]
Delegator with no deposits or staking in any node operator proceeds with claim rewards with resultant transaction failing on blockchain while delegator loses 2.058 zil as Zill fee.

This can be avoided if Claim Rewards button is disabled for delegator with no rewards whatsoever. Also, further check of only allowing to proceed with node operator where delegator has any rewards to be claim.

Please refer attached word doc for further details.
[UX Issue3.docx](https://github.com/Zilliqa/Zillion-issue/files/5249788/UX.Issue3.docx)

**Comment by AmritKumar** [comment]
Thanks for the input. The UI will now prevent delegators from calling ClaimRewards if they haven't staked yet. I am closing this for now.
![image](https://user-images.githubusercontent.com/4191868/94534192-00d03000-0238-11eb-93a6-4dfff12c44ea.png)
