### ISSUE TITLE
rename re-delegate button to move stake (or something else)

### ISSUE THREAD

**Issue by mwansich** [Zilliqa/Zillion-issue#6]
name is misleading because it doesnt actually withdraw and delegate again (hence re-delegate) but only moves stake from one ssn to another.
Also the button in the dashboard says "re-delegate stake" and the button in the modal just says "re-stake", should be the same.

**Comment by AmritKumar** [comment]
Thanks for the suggestion. The button is now changed to "Transfer Stake"
![image](https://user-images.githubusercontent.com/4191868/94044594-45864200-fdc6-11ea-9507-f0ce1a68e4f5.png)

**Comment by AmritKumar** [comment]
Closing this for now.
