### ISSUE TITLE
re-delegating stake doesnt work

### ISSUE THREAD

**Issue by mwansich** [Zilliqa/Zillion-issue#7]
zilpay tells me i dont have enough funds available when trying to re-stake (see screenshot)
was only possible to re-stake a quarter of the actual delegated funds but transaction failed
https://viewblock.io/zilliqa/tx/125c30f2e42b1b7bfc6dd478c379eb64d8805c428c68bc8ca115f8bd079c6ea4?network=testnet

![Screenshot 2020-09-19 at 23 50 20](https://user-images.githubusercontent.com/70520740/93689859-efb64f00-fad2-11ea-90e5-b80c83d7412d.jpg)
![Screenshot 2020-09-19 at 23 50 01](https://user-images.githubusercontent.com/70520740/93689861-f2b13f80-fad2-11ea-8543-ba6cfe05e6b1.jpg)

**Comment by 10131** [comment]
I have the same issue even though I have enough ZIL to do the transaction. Here's a gif of it.

![2020-09-20 19 53 06](https://user-images.githubusercontent.com/71618874/93729917-48412700-fb7b-11ea-8d7f-073534a70b89.gif)

**Comment by WuZenKey** [comment]
Oh well made - glad someone else had the same issue - makes me feel like I
wasn’t missing something.

Thank you.

**Comment by AmritKumar** [comment]
Good catch folks. This is indeed a bug. We will fix it. I will keep this issue open for now.

**Comment by AmritKumar** [comment]
This is fixed. Thanks again. We have also changed the UI a bit too. Closing it for now.
![image](https://user-images.githubusercontent.com/4191868/94140744-9f891500-fe63-11ea-80eb-40ed30144f0e.png)
