### ISSUE TITLE
Gzil not tranferred

### ISSUE THREAD

**Issue by andreaxxyxx** [Zilliqa/Zillion-issue#8]
Hello, in testnet I claimed the accrued _Zil rewards: I got them but without any attached Gzil.
As "These gZILs are sent to your address along with your ZIL rewards" I suppose something is not going as expcted.

**Comment by FlipOne513** [comment]
Wondering the same thing.

**Comment by AmritKumar** [comment]
You can see your $gZIL [here](https://viewblock.io/zilliqa/address/zil10w2fwf5kdwqvjd2zyv6nr7da2d2z63g5dvtvsy?network=testnet&tab=holders). I am closing this as this is not an issue. Please open it back if you do not see your balance there.
